name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ecs:
    name: ECS Check
    runs-on: ubuntu-latest
    env:
      DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-ansi --no-progress --no-suggest"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run ecs check
        run: |
          composer run-script ecs-check
  rector:
    name: Rector dry-run
    runs-on: ubuntu-latest
    env:
      DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-ansi --no-progress --no-suggest"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run rector --dry-run
        run: |
          composer run-script rector-dry-run
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    env:
      DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-ansi --no-progress --no-suggest"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run phpstan
        run: |
          composer run-script phpstan
